version: '3.8'

services:
  mongodb:
    hostname: mongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ../DB/localMongoData/db:/data/db
  app:
    depends_on:
      - mongodb
    image: hackarmour/discord-assistant:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TOKEN=$TOKEN
      - CLIENTID=$CLIENTID
      - mongodbUrl="mongodb://localhost:27017/Assistant"
      - GUILDID=$GUILDID
    stdin_open: true
    tty: true

volumes:
  db: