name: Release

on:
  push:
    branches: [ 'main' ]

jobs:

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [ tests ]
    strategy:
      matrix:
        node-version: [16.x]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: ${{ secrets.BOT_TOKEN }} 
          CLIENTID: ${{ secrets.BOT_CLIENT_ID }} 
          GUILDID: ${{ secrets.TESTING_GUILD_ID }}
